#!/usr/bin/env node

const table = require("markdown-table");
const fs = require("fs");
const data = require("../src/data.json");

const headers = [
  "Package",
  "Version",
  "Automatic Vendor Prefixing",
  "Pseudo Classes",
  "Media Queries",
  "Styles As Object Literals",
  "Extract CSS File"
];

const link = obj => `[${obj.text}](${obj.href})`;
const links = objs => objs.map(link).join(" + ");
const version = obj => obj;
const symbol = obj => (obj === true ? "✓" : "");

const row = obj =>
  headers.map(header => {
    if (header === "Package") {
      return links(obj[header]);
    } else if (header === "Version") {
      return version(obj[header]);
    } else {
      return symbol(obj[header]);
    }
  });

const rows = data.rows.map(row);
rows.unshift(headers);

let text = fs.readFileSync("../README.md", "utf8");

if (text.indexOf("<!-- autogenerated table start -->") === -1) {
  console.log(
    `Error! Please, place tags around the table \n<!-- autogenerated table start --> table <!-- autogenerated table end -->`
  );
  process.exit(1);
}

text = text.replace(
  /<!-- autogenerated table start -->[\s\S]*?<!-- autogenerated table end -->/,
  `<!-- autogenerated table start -->\n${table(
    rows
  )}\n<!-- autogenerated table end -->`
);
fs.writeFileSync("../README.md", text, "utf8");
