#!/usr/bin/env node

const table = require("markdown-table");
const fs = require("fs");
const data = require("../src/data.json");

const headers = [
  "Package",
  "Version",
  "Automatic Vendor Prefixing",
  "Pseudo Classes",
  "Media Queries",
  "Styles As Object Literals",
  "Extract CSS File"
];

const link = obj => `[${obj.text}](${obj.href})`;
const links = objs => objs.map(link).join(" + ");
const version = obj => obj;
const symbol = obj => (obj === true ? "✓" : "");

const formatters = {
  Package: links,
  Version: version,
  default: symbol
};

const defaultFallback = (options, field) => options[field] || options.default;

const row = obj =>
  headers.map(header => {
    const formatter = defaultFallback(formatters, header);
    return formatter(obj[header]);
  });

const rows = data.rows.map(row);
rows.unshift(headers);

let text = fs.readFileSync("../README.md", "utf8");

if (text.indexOf("<!-- autogenerated table start -->") === -1) {
  console.log(
    `Error! Please, place tags around the table \n<!-- autogenerated table start --> table <!-- autogenerated table end -->`
  );
  process.exit(1);
}

const align = headers.map(x => "c");
align[0] = "l";
const pad = false;

text = text.replace(
  /<!-- autogenerated table start -->[\s\S]*?<!-- autogenerated table end -->/,
  `<!-- autogenerated table start -->\n${table(rows, {
    align,
    pad
  })}\n<!-- autogenerated table end -->`
);
fs.writeFileSync("../README.md", text, "utf8");
